fuck it, lots of changes

diff --git a/cq b/cq
--- a/cq
+++ b/cq
@@ -26,7 +26,7 @@ lock() { flock -x $lockfd }
 unlock() { flock -u $lockfd }
 
 kill-cqd() { cqd-running && kill $@ $cqdpid }
-notify-cqd() { kill-cqd -USR1 }
+notify-cqd() { kill-cqd -ALRM }
 
 newjobid() {
     comm -13 <(ls $CQDIR/jobs | egrep '^[0-9]+$' | sort -n) \
@@ -96,6 +96,10 @@ cq-ping() {
     notify-cqd || { echo "cqd not running" >&2; return 1 }
 }
 
+cq-hup() {
+    kill-cqd -HUP || { echo "cqd not running" >&2; return 1 }
+}
+
 cq-start() {
     # FIXME: avoid starting cqd more than once
     export CQDIR
@@ -121,7 +125,7 @@ cq-stop() {
             rm -f $CQDIR/cqd.pid
             if [[ -d $CQDIR/current ]]; then rm -r $CQDIR/current; fi
         else
-            kill -USR2 $cqdpid || die 'could not signal cqd'
+            kill -INT $cqdpid || die 'could not signal cqd'
             if [[ -f $CQDIR/cqd.pid ]] && [[ -d $CQDIR/current ]]; then
                 echo 'cqd will exit after it finishes its current job.'
                 echo 'To kill it immediately, use `cq stop -f`.'
@@ -148,15 +152,6 @@ cq-status() {
     [[ -d $CQDIR/current ]] && echo "current job: $(jobsummary $CQDIR/current)"
 
     unlock
-}
-
-cq-view() {
-    # No locking can save the fundamental issue here - the current job can end
-    # at any time. So we don't do any locking.
-
-    [[ -f $CQDIR/current/pid ]] || die "no current job to view"
-    local pid=$(cat $CQDIR/current/pid)
-    screen -r $pid
 }
 
 cq-list() {
@@ -282,7 +277,7 @@ done
 cmd=$1; shift
 
 case $cmd in
-    add|create|destroy|edit|edit-queue|list|ping|remove|start|status|stop|view)
+    add|create|destroy|edit|edit-queue|hup|list|ping|remove|start|status|stop)
         # command was fully specified, do nothing
         ;;
 
@@ -293,7 +288,6 @@ case $cmd in
     l) cmd=list;;
     r) cmd=remove;;
     s) cmd=status;;
-    v) cmd=view;;
 
     *) echo "unrecognized command: $cmd"; exit 1;;
 esac
